### PR TITLE
ports/nrf/boards/microbit: Backport of microbit display / image modules

### PR DESCRIPTION
**Pull request by glennrub**
Backport of bbc:microbit display and image module. Ref: https://github.com/bbcmicrobit/micropython/tree/master/source/microbit

The modules have been put into a board-modules folder which is only compiled in if the microbit board target is compiled (boards/microbit/modules). This modules Image/display is a pure backport and has minor changes to the original code. 

Also adding a stripped down version of modmicrobit, to facilitate the display/Image modules to be imported through the microbit module.

The code has been modified on areas which required float, in order to make it compile, as floating point for nrf51 targets have been disabled by default in the port.

### CODE REVIEW

**Comment by glennrub** [comment]
Tested with BLE NUS enabled, both music and display can work while BLE link is active on the microbit.

**Comment by glennrub** [comment]
@aykevl Do you think it would be possible to free up a few bytes from the nrf51x22_256k_16k_s110_8.0.0.ld.?  
(EDIT: I mean, taking it from the FLASH_USER)

I'm currently lacking 3K in order to enable modmusic and microbit.display/Image by default when BLE NUS is enabled. I'm thinking maybe 8K, which could make even microbitfs fit inside. 

EDIT2: On a second thought, as this will become a very tight target, i think it is best to just add a custom linker script right away, for microbit+S110.

**Comment by aykevl** [comment]
We could also make the FLASH_USER area somehow variable, i.e. dropping FLASH_USER and using the remaining space for the filesystem. Of course, this means that each new flash could invalidate/corrupt the filesystem if no extra care is taken.
I have a few ideas in mind how this can be done, but should describe them with a clearer head.

**Comment by aykevl** [comment]
On second thought, you're probably right. The micro:bit is a bit different in that it has a pre-existing configuration, with all those extra modules taking up space.
Nonetheless, it would be nice to have this functionality (variable filesystem area) but that's a bit more difficult that creating a new linker script.

**Comment by glennrub** [comment]
Rebased to keep history of changes to ease comparison against original source if need be.

**Pull request merged**
