### PR TITLE
nrf/bluetooth: Add support for s132/s140 v6, remove s132 v2/3/5

### PR DESCRIPTION
**Pull request by glennrub**
Support added for s132/s140 v6 in linker scripts and boards.
Support removed for s132 v2/3/5.

Download script updated to fetch new stacks and removed the
non-supported ones.

ble_drv.c updated to only handle s110 v8, and s132/s140 v6.

ubluepy updated to continue scanning after each individual scan
report reported to the module to keep old behaviour of the
Scanner class.

### CODE REVIEW

**Comment by aykevl** [comment]
I think these files can be removed with this PR:

* boards/s132_3.0.0.ld
* boards/s132_5.0.0.ld

**Comment by aykevl** [comment]
Other than that it looks good (I didn't look at it too closely).

**Comment by glennrub** [comment]
Thanks! I'll remove the leftover .ld files. And also rebase the PR to get an update on the feather52 board config as well.

**Comment by glennrub** [comment]
PR rebased and updated. I'll do some final sanity testing before i merge this using various BLE stacks.

- [x]  BLE REPL s110 + non-connectable advertisment in Link
- [x] BLE REPL s132 + non-connectable advertisment in Link
- [x] BLE REPL s140 + non-connectable advertisment in Link

**Comment by glennrub** [comment]
Blocked on testing microbit as LTO=0 overflows by 9088, due to issues with newer GCC reported in issue #160 LTO has to be disabled. Had to do a manual tuning of the FS size in microbit custom_nrf51822_s110_microbit.ld and set the _fs_size = 2K. After this it is green and works as expected.

Script used for testing while in BLE NUS link:
```
>>> from ubluepy import Peripheral
>>> p = Peripheral()
>>> p.advertise(device_name="microbit", connectable=False)
```

**Pull request merged**
