### PR TITLE
Updates to allow main.py etc. while using NUS

### PR DESCRIPTION
**Pull request by aykevl**
1. Fix Ctrl-C while using the NUS console (doesn't break sleep, however). Also fixes ampy (oops - I should have tested it but it didn't work when I tried it).
2. don't wait for a connection before running scripts. Also, this fixes a somewhat theoretical issue when something is written to stdout after a disconnect.
3. Increase tx speed by about 6x.

### CODE REVIEW

**Comment by aykevl** [comment]
I just realized how I can easily fix the TODO, so please don't merge yet.

**Comment by aykevl** [comment]
Done. It costs ~12 bytes but now the REPL will only be started once the connection is established.

**Comment by aykevl** [comment]
Basically everything has already been merged already in different PRs, so this can be closed.

**Comment by aykevl** [comment]
I think the only thing that's not merged is the output buffer. But I'm not entirely sure we'd want that anyway. Maybe the input buffer can be re-used as output buffer, to save RAM.

**Comment by glennrub** [comment]
Right, the tx_ring_buffer. Could you remind me why that is needed in ble_uart.c on top of 6 notifications that can be queued in for hvx in ble_drv.c?

**Comment by aykevl** [comment]
It's unrelated to the 6 queued notifications. The buffer is/was used to queue up messages before a connection has been made (e.g. a backtrace) to send them once the connection is working.

**Comment by aykevl** [comment]
I found another one: Ctrl-C appears to be broken at the moment.
But that will happen in a new PR, this one is too much out of date.

EDIT: nevermind, I forgot to enable `MICROPY_KBD_EXCEPTION`. It is working now for me.

**Pull request closed without merging**
