### PR TITLE
ports/nrf: DFU to update firmware over BLE.

### LINKED ISSUE #146: DFU/bootloader support
I have written a DFU (device firmware updater) that's written in the 4kB MBR of the SoftDevice. At the moment it is just over 1kB in size, so some extra features could be added (e.g. update on button press at reset, update over serial, more safety, etc.).
A Python script to send a hex file over BLE can be found here: https://github.com/aykevl/pynus/blob/master/dfu.py

This is the branch implementing DFU: https://github.com/tralamazza/micropython/compare/master...aykevl:nrf-dfu-mbr-wip

There are a few things left to do, but I'm putting it here because these are only relatively small changes and some feedback would be welcome.

TODO: 

- [x] test mbr/bootloader mode on nRF51 (should work, but as there were a lot of changes it should be tested again)
- [x] test bootloader mode on nRF52 (find UICR.BOOTLOADERADDR address)
- [ ] support bootloaderaddr in mergehex.py
- [x] fix bootloaderaddr in 'info' characteristic
- [x] optionally load parameters (application start address etc.) from the info struct in the SoftDevice instead of hardcoding it - this makes it possible to update the SoftDevice (including resizing it!) without updating the DFU.
- [x] Python 2 support in mergehex.py
- [x] fix "buffer too small" errors (see https://github.com/tralamazza/micropython/pull/147)

### PR DESCRIPTION
**Pull request by aykevl**
See #146. This is a combination of all the commits.

When a SoftDevice is enabled, automatically enable the DFU in MBR. It will be merged with the SoftDevice and the application to produce a firmware.hex file. A reference uploader (from a computer) is at https://github.com/aykevl/pynus/blob/master/dfu.py.

closes #146.

### CODE REVIEW

**Comment by glennrub** [comment]
Thanks @aykevl! This is great work! Getting a BLE OTA bootloader has been a wish for a long time.
I'll take a look at the code as soon as possible. 

I'm also wondering if it makes sense to add the dfu.py as a tool to be used inside micropython? what do you think? there are already some special targets for dfu-gen and dfu-flash for feather52 in the boards .mk file: 
https://github.com/tralamazza/micropython/blob/master/ports/nrf/boards/feather52/mpconfigboard_s132.mk#L23

If we add a the dfu.py tool and align the make target names a bit, we could have some kind of standard targets like dfu-uart/dfu-ble, to hook in the appropriate transfer tool.  In this case there is only need for dfu-ble. However, i'm thinking that a bootloader in the future might as well support uart transfer when BLE is not present. Thats why i'm suggesting to set some standard targets names.
We can discuss this a bit more later,  I will focus on this PR first.

**Comment by aykevl** [comment]
Regarding UART pins, it's possible to pick them from the mpconfigboard.h configuration: https://github.com/aykevl/micropython/compare/nrf-dfu-mbr...aykevl:nrf-dfu-uart-pins
This compiles down to the exact same code as if the pins had been hardcoded.

**Comment by aykevl** [comment]
Rebased on top of the latest master, resolving a conflict.

**Comment by aykevl** [comment]
This needs more testing. It appears like having a DFU in the MBR affects normal operation.

Ideas to get this to work:
 * Make a regular bootloader anyway. This eats up some space that cannot be used for other things - probably just 1kB on the nrf51.
 * Make a regular bootloader but put it in the space between the SoftDevice and the application. At least on the nrf51, there appears to be about 5.8kB of unused space (s110 version 8.0.0).
 * Maybe see why it doesn't work - is there something the default MBR does that the DFU does different?

**Comment by aykevl** [comment]
Another idea I came up with, which might be rather radical:

* Place the DFU in the first page of the application image, right after the ISR vectors. On boot, if it must enter DFU mode, it copies the code relevant for the DFU into RAM and executes further from there. When a new firmware is flashed, the first page (with the reset vector and the DFU) is erased and flashed last (in one command) to make sure a dropped connection will not brick the device. The only vulnerable time is between erasing the reset vector and writing it, which can all be done at once and doesn't depend on an active connection.

**Comment by aykevl** [comment]
Again rebased on top of current master and modified a little to accomodate the nrfx changes.

I think it is possible (and the best approach now) to make the DFU a regular bootloader. It should be put in an area of flash, probably between FLASH_TEXT and FLASH_USER. I think it is possible to do this without duplicating all linker scripts but this needs some experimenting, so this PR is a work in progress.

---

Regarding the DFU script: I'm not sure whether copying it is such a good idea. Maybe it can be added as a submodule, although I don't really like that either.

**Comment by aykevl** [comment]
Rebased on top of current master (with a few minor whitespace changes) and added a few commits.
The last one shows why I've gone through the effort of making the linker scripts more modular: only a small change was required in one linker script to resize the app depending on the presence of a bootloader.

What I'd like to do:

 * Change the protocol to make it easier to support updating the SD and adding cryptographic signatures in the future.
 * Somehow make the updater script check that a new app image doesn't place the filesystem in the bootloader area (e.g. by forgetting to pass `DFU=bootloader` when compiling the new firmware).

**Comment by glennrub** [comment]
In order to clean up a bit i'm closing this PR as the continuation of the nrf-port development should happen in mainline micropython repository after the merge.

**Pull request closed without merging**
