### PR TITLE
nrf: Make linker scripts more modular.

### PR DESCRIPTION
**Pull request by aykevl**
With all the variation in chips and boards it's tedious to copy and redefine linker scripts for every option. Making linker scripts more modular also opens up more possibilities, like enabling/disabling the flash file system from the Makefile - or even defining it's size from a Makefile argument. For example `FS_SIZE=4` for a 4kB filesystem if tight on space or `FS_SIZE=0` to disable the filesystem altogether.

**This is a work in progress.** Making a pull request just to show what I'd like to do, for discussion. I have only quickly tested the pca10040 (without SD, with SD, with SD and NUS). The other boards have only been tested by compiling. Only a few boards have been converted to the new system.

### CODE REVIEW

**Comment by aykevl** [comment]
I have now updated all board definitions to the new linker script system and I think it's ready for review/merge.

While building with the flash file system enabled (`MICROPY_HW_HAS_BUILTIN_FLASH`) I compared the .hex files before and after these changes, and they are identical except for the micro:bit with a disabled SoftDevice. My guess is that this is because I have set the flash filesystem size to 12K always on the micro:bit whether it uses a SoftDevice or not. This should be fixed at some point but as the flash filesystem is disabled by default I don't think this is an issue.

Note that this change **removes support** for SoftDevice s120 and s130. I doubt they actually worked and re-adding support shouldn't be very difficult.

For reference, these are the md5sums on my system (Debian stretch, `arm-none-eabi-gcc (15:5.4.1+svn241155-1) 5.4.1 20160919`, commit fd91c0c7 dirty, with flash FS enabled):

```
6f0fa569f084a8e22a1bced8408f3884  ./build-arduino_primo/firmware.hex
0827133a657d3e4a21af4403894e293a  ./build-arduino_primo-s132/firmware.hex
05baa23723759e8a52100e9c0d8f3bbd  ./build-dvk_bl652/firmware.hex
7c1b26f9050794e6ddb53e2f2ff6544a  ./build-dvk_bl652-s132/firmware.hex
082fdc0c5a8b1746657568085eb41128  ./build-feather52/firmware.hex
2f616719bed9005db7eb9a7c93f19eae  ./build-feather52-s132/firmware.hex
f30fb11de2b58c65258d0972c566ef1a  ./build-microbit/firmware.hex
d314a7cb739ddfe9010c4a011eeb0b20  ./build-microbit-s110/firmware.hex
fd08af512b67ff63b11203c70a9ce7e5  ./build-pca10000/firmware.hex
73cd248a5b742023981dd091b41dd6b6  ./build-pca10000-s110/firmware.hex
eb134a95f2fa4e7baded1821b278dc71  ./build-pca10001/firmware.hex
4205d55e6b017a39cac154b89a2a4486  ./build-pca10001-s110/firmware.hex
fb7f643dbf128323ec0e03bcd057a186  ./build-pca10028/firmware.hex
03afd25369929a2312bd62667e22cb52  ./build-pca10028-s110/firmware.hex
67beb894b470762901acfb1a53f0213a  ./build-pca10031/firmware.hex
ebf38de7fe23e52f11faf18588a93350  ./build-pca10031-s110/firmware.hex
cb1755af092c269e57548cb4ff9cb803  ./build-pca10040/firmware.hex
acf016f5418daca8cd21b524d85314f5  ./build-pca10040-s132/firmware.hex
fe711c9a7baf16c878a19087daaab876  ./build-pca10056/firmware.hex
09b4f1104bc22c9d33acd3471ea0cb6b  ./build-wt51822_s4at/firmware.hex
af2ef5cae96fee56139ff432cb415884  ./build-wt51822_s4at-s110/firmware.hex
```

**Comment by aykevl** [comment]
Update: now the issue with the micro:bit board is fixed, all boards compile with the same hex file md5sum. My guess was correct - it should only force the flash filesystem size to 12K when a SoftDevice is in use.

Oh and I haven't actually ran these builds on a real board, I only built them. But as the hex files are equal there can't be any change in the resulting firmware (the file that is actually flashed to the board).

**Comment by glennrub** [comment]
I really like what you have done here @aykevl!

How do you consider this PR? is it merge ready from your side? For me it looks good.

You are right, the s120/s130 support is outdated. I had a plan to keep them working for a long time. I believe we can deprecate them now, and re-introduce them if there is a strong wish for central role on nrf51.

**Comment by aykevl** [comment]
I don't really like having dead code around. It makes other changes more difficult. It should be easy enough to add support for s120 and s130 if the need arises - if it ever arises. It is only a linker script, nothing more (it doesn't even compile).

In my opinion it can be merged, though I would feel a bit more confident if a few of the more difficult targets were tested first (feather52, micro:bit). Even though this should not matter with the validation I've done.

**Comment by glennrub** [comment]
I've tested it using microbit with and without BLE. Works like a charm! Merging this.

**Pull request merged**
