### PR TITLE
Adding a README for the nRF5 port

### PR DESCRIPTION
**Pull request by mattytrentini**
I've started a README for the nRF5 port. Please take a look and let me know if you'd like me to change or add anything.

### CODE REVIEW

**Comment by glennrub** [comment]
Hi Matt! Thanks for the PR! 

I'll merge it in right away! This is a good start! 
I think next step would be to also document the SD parameter. Some content has been written on this  in the wiki and would make sense to move into the readme now.

Cheers!

**Comment by mattytrentini** [comment]
Glad it was somewhat useful. :)

I'll try to fill it out as time allows; in particular I'd prefer to have the examples less device-specific.  I think it'd be better to document the build process _generally_ (ie not tied to the Feather) and only not where it _has_ to become device-specific. 

I'd also like to put together a docker build container that could be referred to in the documentation...

**Comment by glennrub** [comment]
Awesome! Appreciate all help we can get :-)
I created #46 and #47, if you are interested in following up a bit on the doc.

Docker containers sounds interesting. I haven't used much of those yet. Maybe it could make sense for nrfjprog (JLink) and pyocd (DAP) targets as well?

**Comment by glennrub** [comment]
Hi Matt!

We have started to prepare for doing a PR to upstream micropython master. The aim is late next week. In that context i have done an update on the readme file (#59). It would be great if have some time to take a look and give some feedback. 

Cheers!

**Pull request merged**
